spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waguwagu_order?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 192.168.0.26
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/waguwagu
