spring:
  data:
    redis:
      host: waguwagu-waguwagu-redis
      port: 6379

    mongodb:
      uri: mongodb://localhost:27017/waguwagu

  kafka:
    bootstrap-servers: 34.71.194.186:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: order
      auto-offset-reset: earliest

jwt:
  secret: gbjksdsejkeruu2357597599#@@#@#@dhfsdhn
  expiration: 25920000

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always